<a href="https://colab.research.google.com/github/YAMSANISAHITHI/2216125_AIML_BootCamp/blob/main/Assingment9(dataset1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t',header=None, names=['label','message'])

In [5]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.shape

(5572, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [8]:
#Data processing
#Method-1:Label Encoder
#Method-2
df['label']=df.label.map({'ham':0,'spam':1})

In [9]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [10]:
#Load the data
X=df.iloc[:,-1:].values
Y=df.iloc[:,:-1].values


In [11]:
X

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [12]:
Y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [13]:
#Splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1,shuffle=True)

In [14]:
X_train.shape

(4457, 1)

In [15]:
X_test.shape

(1115, 1)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
#Transform the Training data into freqq vectors and return the matrix
training_data=count_vector.fit_transform(X_train.flatten())
#Transform the Testing data into freq vectors and return the matrix
testing_data=count_vector.transform(X_test.flatten())

In [44]:
#naive bayes
from sklearn.naive_bayes import MultinomialNB
model1= MultinomialNB()

In [45]:
model1.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [46]:
y_pred=model1.predict(testing_data)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [47]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [48]:
print("Predicted value for training data:",model1.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model1.score(testing_data,Y_test)*100)  

Predicted value for training data: 99.23715503702041
Predicted value for testing data: 99.01345291479821


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FP FN TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model1.predict(training_data))
print(cm1)

confusion matrix for testing data
[[965   3]
 [  8 139]]
confusion matrix for traning data
[[3843   14]
 [  20  580]]


In [50]:
#randomforest
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [51]:
y_pred=model2.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [52]:
print("Predicted value for training data:",model2.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model2.score(testing_data,Y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 98.11659192825111


In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model2.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 21 126]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [28]:
#decisiontree
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier()

In [29]:
model3.fit(training_data,Y_train)

DecisionTreeClassifier()

In [30]:
print("Predicted value for training data:",model3.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model3.score(testing_data,Y_test)*100)  

Predicted value for training data: 100.0
Predicted value for testing data: 97.30941704035875


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model3.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 17 130]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [32]:
#logisticregression
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression()

In [34]:
model4.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [35]:
print("Predicted value for training data:",model4.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model4.score(testing_data,Y_test)*100)  

Predicted value for training data: 99.75319721785955
Predicted value for testing data: 98.9237668161435


In [54]:
y_pred=model4.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model4.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 17 130]]
confusion matrix for traning data
[[3857    0]
 [  11  589]]


In [39]:
#knn
from sklearn.neighbors import KNeighborsClassifier
model5=KNeighborsClassifier()

In [40]:
model5.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [41]:
print("Predicted value for training data:",model5.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model5.score(testing_data,Y_test)*100)  

Predicted value for training data: 93.56069104778999
Predicted value for testing data: 92.37668161434978


In [42]:
y_pred=model5.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model5.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 85  62]]
confusion matrix for traning data
[[3857    0]
 [ 287  313]]


In [55]:
#svc
from sklearn.svm import SVC
model6=SVC()
model6.fit(training_data,Y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [56]:
print("Predicted value for training data:",model6.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model6.score(testing_data,Y_test)*100)  

Predicted value for training data: 99.50639443571909
Predicted value for testing data: 98.7443946188341


In [57]:
y_pred=model6.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model6.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 13 134]]
confusion matrix for traning data
[[3857    0]
 [  22  578]]
